#!/usr/bin/env python3

import argparse
import subprocess
import sys
import os

def main(file):
    readFile(file)
    pass

def readFile(file_name):
    with open(file_name) as fp:
        for line in fp:
            command = "./cpplint.py {0}".format(line.rstrip("\n"))
            subprocess.call(command, shell = True);
    pass

if __name__ == '__main__':
    main(sys.argv[1])
