#!/usr/bin/env bash

INIT_FILE='tmp_files.dat'
TRIM_FILE='tmp_files_2.dat'
NO_LEAD_FILE='files.dat'
OUTPUT_FILE='output.dat'

find_files ()
{
    find -name "*.cpp" > "$INIT_FILE"
    find -name "*.h" >> "$INIT_FILE"
}

trim_log ()
{
    cat "$INIT_FILE" | cut -c3- > "$TRIM_FILE"
}

clean ()
{
    rm "$INIT_FILE"
    rm "$TRIM_FILE"
    rm "$NO_LEAD_FILE"
}

find_files
trim_log
grep . "$TRIM_FILE" --no-messages > "$NO_LEAD_FILE"

./lineReader "$NO_LEAD_FILE" > "$OUTPUT_FILE" 2>&1
clean
